//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoutingServer.ProxyCache {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyCache.IServerProxy")]
    public interface IServerProxy {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerProxy/GetAvailabilities", ReplyAction="http://tempuri.org/IServerProxy/GetAvailabilitiesResponse")]
        string GetAvailabilities(string station, string contract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerProxy/GetAvailabilities", ReplyAction="http://tempuri.org/IServerProxy/GetAvailabilitiesResponse")]
        System.Threading.Tasks.Task<string> GetAvailabilitiesAsync(string station, string contract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerProxy/GetStations", ReplyAction="http://tempuri.org/IServerProxy/GetStationsResponse")]
        string GetStations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerProxy/GetStations", ReplyAction="http://tempuri.org/IServerProxy/GetStationsResponse")]
        System.Threading.Tasks.Task<string> GetStationsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServerProxyChannel : RoutingServer.ProxyCache.IServerProxy, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServerProxyClient : System.ServiceModel.ClientBase<RoutingServer.ProxyCache.IServerProxy>, RoutingServer.ProxyCache.IServerProxy {
        
        public ServerProxyClient() {
        }
        
        public ServerProxyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServerProxyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerProxyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerProxyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetAvailabilities(string station, string contract) {
            return base.Channel.GetAvailabilities(station, contract);
        }
        
        public System.Threading.Tasks.Task<string> GetAvailabilitiesAsync(string station, string contract) {
            return base.Channel.GetAvailabilitiesAsync(station, contract);
        }
        
        public string GetStations() {
            return base.Channel.GetStations();
        }
        
        public System.Threading.Tasks.Task<string> GetStationsAsync() {
            return base.Channel.GetStationsAsync();
        }
    }
}
